#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun  2 22:49:22 2019

@author: jim
"""
import pandas as pd
My='submit.csv'
Xu='xujiansubmmit.csv'
mm=pd.read_csv(My)
xx=pd.read_csv(Xu)